export const MAX_DAILY_WITHDRAWAL_LIMIT = 400;
export const MAX_INDIVIDUAL_WITHDRAWAL_LIMIT = 200;
export const WITHDRAWAL_INCREMENT = 5;

export const MAX_INDIVIDUAL_DEPOSIT = 1000;
export const MIN_INDIVIDUAL_DEPOSIT = 0.01;
